# Generated by Django 2.1.3 on 2018-11-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='from_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='to_time',
            field=models.TimeField(null=True),
        ),
    ]
